# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # ✅ Autenticadores (formulário + Google OAuth2)
            custom_authenticators:
                - App\Security\GoogleAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_dashboard

            logout:
                path: app_logout
                target: app_login

            entry_point: form_login

    access_control:
        # ✅ Áreas públicas
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/cadastro, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS } # ⚠️ necessário para rotas do Google OAuth

        # ✅ Áreas protegidas
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/avaliacoes-defesa, roles: ROLE_USER }
        - { path: ^/avaliacoes-qualificacao, roles: ROLE_USER }
        - { path: ^/defesa-form, roles: ROLE_USER }
        - { path: ^/quali-form, roles: ROLE_USER }
        - { path: ^/inserir-trabalho, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
